package com.biblioteca.view;

import com.biblioteca.model.EmprestimoLivroModel;
import com.biblioteca.model.EmprestimoLocatarioModel;
import com.biblioteca.model.EmprestimoModel;
import com.biblioteca.model.LivroModel;
import com.biblioteca.model.LocadorModel;
import com.biblioteca.model.LocatarioModel;
import com.biblioteca.service.EmprestimoLivroService;
import com.biblioteca.service.EmprestimoLocatarioService;
import com.biblioteca.service.EmprestimoService;
import com.biblioteca.service.LivroService;
import com.biblioteca.service.LocadorService;
import com.biblioteca.service.LocatarioService;
import com.biblioteca.util.GetDateUtil;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author José Luiz
 */
public class FrmEmprestimo extends javax.swing.JInternalFrame {

    LocatarioModel locatarioModel = new LocatarioModel();
    LocatarioService locatarioService = new LocatarioService();
    ArrayList<LocatarioModel> listaLocatarioModel = new ArrayList<>();

    LocadorModel locadorModel = new LocadorModel();
    LocadorService locadorService = new LocadorService();
    ArrayList<LocadorModel> listaLocadorModel = new ArrayList<>();

    LivroModel livroModel = new LivroModel();
    LivroService livroService = new LivroService();
    ArrayList<LivroModel> listaLivroModel = new ArrayList<>();

    EmprestimoModel emprestimoModel = new EmprestimoModel();
    EmprestimoService emprestimoService = new EmprestimoService();
    ArrayList<EmprestimoModel> listaEmprestimoModel = new ArrayList<>();

    EmprestimoLocatarioModel emprestimoLocatarioModel = new EmprestimoLocatarioModel();
    EmprestimoLocatarioService emprestimoLocatarioService = new EmprestimoLocatarioService();
    ArrayList<EmprestimoLocatarioModel> listaEmprestimoLocatarioModel = new ArrayList<>();

    EmprestimoLivroModel emprestimoLivroModel = new EmprestimoLivroModel();
    EmprestimoLivroService emprestimoLivroService = new EmprestimoLivroService();
    ArrayList<EmprestimoLivroModel> listaEmprestimoLivroModel = new ArrayList<>();

    EmprestimoLivroModel livrosEmprestimosLivrosModel = new EmprestimoLivroModel();
    EmprestimoLivroService livrosEmprestimosLivrosService = new EmprestimoLivroService();
    ArrayList<EmprestimoLivroModel> listaLivrosEmprestimosLivrosModel = new ArrayList<>();

    GetDateUtil getDateUtil = new GetDateUtil();

    /**
     * Creates new form FrmEmprestimo
     */
    public FrmEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfAutor1 = new javax.swing.JTextField();
        jtfAutor2 = new javax.swing.JTextField();
        jcbTitulo = new javax.swing.JComboBox<>();
        jlQtde = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbLocador = new javax.swing.JComboBox<>();
        jcbLocatario = new javax.swing.JComboBox<>();
        jtfDataEmprestimo = new javax.swing.JFormattedTextField();
        jtfDataDevolucao = new javax.swing.JFormattedTextField();
        jlAdicionar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAdicionarEmprestimo = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jbRemoverItens = new javax.swing.JButton();
        jbEmprestar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtListarEmprestimo = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDevolucao = new javax.swing.JTable();
        jbDevolver = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("EMPRÉSTIMOS E DEVOLUÇÕES");

        jPanel1.setBackground(new java.awt.Color(28, 89, 124));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TÍTULO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1° AUTOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QUANTIDADE DISPONÍVEL");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GÊNERO (CATEGORIA)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2° AUTOR");

        jtfAutor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfAutor1.setForeground(new java.awt.Color(255, 255, 255));

        jtfAutor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfAutor2.setForeground(new java.awt.Color(255, 255, 255));

        jcbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcbTitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE UM LIVRO" }));
        jcbTitulo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbTituloPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jlQtde.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlQtde.setForeground(new java.awt.Color(255, 255, 255));
        jlQtde.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlQtde.setText("$0");

        jlCategoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jlCategoria.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlCategoria.setText("$CATEGORIA");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("LOCADOR");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LOCATÁRIO");
        jLabel9.setAutoscrolls(true);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATA EMPRÉSTIMO");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DEVOLUÇÃO");

        jcbLocador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcbLocador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE UM LOCADOR" }));

        jcbLocatario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcbLocatario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE UM LOCATÁRIO" }));

        try {
            jtfDataEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataEmprestimo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jtfDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataDevolucao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlAdicionar.setBackground(new java.awt.Color(255, 102, 0));
        jlAdicionar.setDisplayedMnemonic('4');
        jlAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jlAdicionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAdicionar.setText("ADICIONAR");
        jlAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlAdicionarMouseClicked(evt);
            }
        });

        jtAdicionarEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Título", "Data Empréstimo", "Data Devolução", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtAdicionarEmprestimo);
        if (jtAdicionarEmprestimo.getColumnModel().getColumnCount() > 0) {
            jtAdicionarEmprestimo.getColumnModel().getColumn(0).setResizable(false);
            jtAdicionarEmprestimo.getColumnModel().getColumn(1).setResizable(false);
            jtAdicionarEmprestimo.getColumnModel().getColumn(2).setResizable(false);
            jtAdicionarEmprestimo.getColumnModel().getColumn(3).setResizable(false);
            jtAdicionarEmprestimo.getColumnModel().getColumn(4).setResizable(false);
        }

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbRemoverItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/lixeira.png"))); // NOI18N
        jbRemoverItens.setText("REMOVER ITENS");
        jbRemoverItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverItensActionPerformed(evt);
            }
        });

        jbEmprestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/emprestar.png"))); // NOI18N
        jbEmprestar.setText("EMRESTAR");
        jbEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEmprestarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAutor1)
                                    .addComponent(jcbTitulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAutor2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlQtde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(56, 56, 56)
                                .addComponent(jcbLocatario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDataEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(jtfDataDevolucao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(66, 66, 66)
                                .addComponent(jcbLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoverItens)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEmprestar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jcbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jtfAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jtfAutor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jlQtde))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jlCategoria))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcbLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jcbLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jtfDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jlAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbRemoverItens)
                    .addComponent(jbEmprestar))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empréstimo", jPanel1);

        jPanel2.setBackground(new java.awt.Color(28, 89, 124));

        jtListarEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Livro", "Locador", "Locatário", "Empréstimo", "Devolução", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtListarEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListarEmprestimoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtListarEmprestimo);
        if (jtListarEmprestimo.getColumnModel().getColumnCount() > 0) {
            jtListarEmprestimo.getColumnModel().getColumn(0).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(1).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(2).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(3).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(4).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(5).setResizable(false);
            jtListarEmprestimo.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Empréstimos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(28, 89, 124));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SELECIONE O EMPRÉSTIMO NA TABELA E CLIQUE EM FAZER DEVOLUÇÃO");

        jtDevolucao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtDevolucao);

        jbDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/devolver.png"))); // NOI18N
        jbDevolver.setText("FAZER DEVOLUÇÃO");
        jbDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 196, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(188, 188, 188))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDevolver)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbDevolver)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Devolver Livro", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        corLinhaTabela();
        setarData();
        limparCampos();
        listarLocatarios();
        listarLocadores();
        listarLivros();
        carregarEmprestimo();
        carregarLivroDevolucao();
        habilitarDesabilitarCampos(false);
        jbNovo.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbRemoverItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverItensActionPerformed
         int linha = jtEmprestimoLivro.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jtEmprestimoLivro.getModel();
        modelo.removeRow(linha);
    }//GEN-LAST:event_jbRemoverItensActionPerformed

    private void jbEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmprestarActionPerformed
       liberarEmprestimo();
        jbNovo.setEnabled(true);
        habilitarDesabilitarCampos(false);
        limparCampos();
        listarLocatarios();
        listarLocadores();
        listarLivros();
        carregarEmprestimo();
        carregarLivroDevolucao();
        listaEmprestimoModel = new ArrayList<>();
    }//GEN-LAST:event_jbEmprestarActionPerformed

    private void jlAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlAdicionarMouseClicked
       adicionarLivroTabela();
    }//GEN-LAST:event_jlAdicionarMouseClicked

    private void jbDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDevolverActionPerformed
        rivate void jbDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {
        Object[] opcoes = {"Sim", "Não"};
        Object resposta;
        resposta = JOptionPane.showInputDialog(null, "Registrar devolução do(s) livro(s)", "Registrar?",
                JOptionPane.OK_CANCEL_OPTION, null, opcoes, "Sim");
        if (resposta.equals("Sim")) {
            int linha = jtDevolucaoLivro.getSelectedRow();
            int codigoEmprestimo = (int) jtDevolucaoLivro.getValueAt(linha, 0);

            listaLivrosEmprestimosLivrosModel = livrosEmprestimosLivrosService
                    .getListaLivrosVendasLivrosDAO(codigoEmprestimo);

            emprestimoModel = emprestimoService.getEmprestimoDAO(codigoEmprestimo);
            for (int i = 0; i < listaLivrosEmprestimosLivrosModel.size(); i++) {

                livroModel = new LivroModel();
                emprestimoLivroModel = new EmprestimoLivroModel();

                livroModel.setIdLivro(listaLivrosEmprestimosLivrosModel.get(i).getLivroModel().getIdLivro());
                livroModel.setQuantidadeLivro(
                        (listaLivrosEmprestimosLivrosModel.get(i).getLivroModel().getQuantidadeLivro()
                        + listaLivrosEmprestimosLivrosModel.get(i).getEmprestimoLivroModel()
                                .getQuantidadeEmprestimo()));

                emprestimoModel.setStatus("INATIVO");
                emprestimoModel.setIdLivro(listaLivrosEmprestimosLivrosModel.get(i).getLivroModel().getIdLivro());
                emprestimoModel.setDataDevolucao(String.valueOf(jtDevolucaoLivro.getValueAt(linha, 4)));
                emprestimoModel.setDataEmprestimo(String.valueOf(jtDevolucaoLivro.getValueAt(linha, 3)));

                livroModel.setQuantidadeLivro(1);
                listaLivroModel.add(livroModel);
            }

            try {
                livroService.alterarEstoqueLivroDAO(listaLivroModel);
                emprestimoService.atualizarEmprestimoDAO(emprestimoModel);
                JOptionPane.showMessageDialog(this, "Livro devolvido com sucesso!", "Atenção",
                        JOptionPane.WARNING_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao registrar a devolução", "Erro", JOptionPane.ERROR_MESSAGE);
                LogModel.logClass = this.getClass().getName();
                new LogCat().writeFile(String.valueOf(e));
            }
    }//GEN-LAST:event_jbDevolverActionPerformed

    private void jtListarEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListarEmprestimoMouseClicked
        // TODO add your handling code here: excluir
    }//GEN-LAST:event_jtListarEmprestimoMouseClicked

    private void jcbTituloPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbTituloPopupMenuWillBecomeInvisible
        if (jcbTitulo.isVisible()) {
            exibirQuantidadeLivro();
        }
    }//GEN-LAST:event_jcbTituloPopupMenuWillBecomeInvisible

 private void listarLocatarios() {

        try {
            listaLocatarioModel = locatarioService.getListaLocatarioDAO();
            jcbLocatario.removeAllItems();
            int cont = listaLocatarioModel.size();
            for (int i = 0; i < cont; i++) {
                jcbLocatario.addItem(listaLocatarioModel.get(i).getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os locatários", "Erro", JOptionPane.ERROR);
            LogModel.logClass = this.getClass().getName();
            new LogCat().writeFile(String.valueOf(e));
        }
    }

    private void listarLocadores() {

        try {
            listaLocadorModel = locadorService.getListaLocadorDAO();
            jcbLocador.removeAllItems();
            int cont = listaLocadorModel.size();
            for (int i = 0; i < cont; i++) {
                jcbLocador.addItem(listaLocadorModel.get(i).getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os locadores", "Erro", JOptionPane.ERROR);
            LogModel.logClass = this.getClass().getName();
            new LogCat().writeFile(String.valueOf(e));
        }
    }

    private void listarLivros() {
        try {
            listaLivroModel = livroService.getListaLivroDAO();
            jcbLivro.removeAllItems();
            int cont = listaLivroModel.size();
            for (int i = 0; i < cont; i++) {
                if (listaLivroModel.get(i).getQuantidadeLivro() > 0) {
                    if (listaLivroModel.get(i).getTipoLivro().equals("EMPRÉSTIMO")) {
                        jcbLivro.addItem(listaLivroModel.get(i).getTitulo());
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao listar os livros", "Erro", JOptionPane.ERROR);
            LogModel.logClass = this.getClass().getName();
            new LogCat().writeFile(String.valueOf(e));
        }
    }

    private void preencherCampos() {
        livroModel = livroService.getLivroDAO(jcbLivro.getSelectedItem().toString());
        jlQuantidade.setText(String.valueOf(livroModel.getQuantidadeLivro()));
        jtfAutor.setText(String.valueOf(livroModel.getAutor()));
        jlCategoria.setText(String.valueOf(livroModel.getCategoria()));
    }

    private void carregarEmprestimo() {
        /**
         * Array que buscará no BD (atraves do Controller) os dados para serem
         * exibidos na tabela
         */
        DefaultTableModel modelo = (DefaultTableModel) jtEmprestimo.getModel();
        listaEmprestimoLocatarioModel = emprestimoLocatarioService.getListaEmprestimosLocatarioDAO();
        // Setando a quantidade de linhas que a tabela para não haver duplicação de
        // dados
        modelo.setNumRows(0);

        try {
            // insere os produtos na tabela
            int cont = listaEmprestimoLocatarioModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(
                        new Object[]{listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getIdEmprestimo(),
                            listaEmprestimoLocatarioModel.get(i).getLivroModel().getTitulo(),
                            listaEmprestimoLocatarioModel.get(i).getLocadorModel().getNome(),
                            listaEmprestimoLocatarioModel.get(i).getLocatarioModel().getNome(),
                            listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getDataEmprestimo(),
                            listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getDataDevolucao(),
                            listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getStatus()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar livros para preencher a tabela\n" + e.toString());
            LogModel.logClass = this.getClass().getName();
            new LogCat().writeFile(String.valueOf(e));
        }
    }

    private void exibirQuantidadeLivro() {
        jlQuantidade.setEnabled(true);
        jlCategoria.setEnabled(true);
        jtfAutor.setEnabled(true);

        livroModel = livroService.getLivroDAO(jcbLivro.getSelectedItem().toString());

        jlQuantidade.setText(String.valueOf(livroModel.getQuantidadeLivro()));
        jlCategoria.setText(livroModel.getCategoria());
        jtfAutor.setText(livroModel.getAutor());

    }

    private void setarData() {
        jtfDataEmprestimo.setText(getDateUtil.getDateTime());
        jtfDataDevolucao.setText(getDateUtil.getDateTimeMonth());

    }

    private void habilitarDesabilitarCampos(boolean condicao) {
        jtfAutor.setEnabled(condicao);
        jtfDataDevolucao.setEnabled(condicao);
        jtfDataEmprestimo.setEnabled(condicao);
        jcbLivro.setEnabled(condicao);
        jcbLocador.setEnabled(condicao);
        jcbLocatario.setEnabled(condicao);
        jbEmprestar.setEnabled(condicao);
        jlCategoria.setEnabled(condicao);
        jlQuantidade.setEnabled(condicao);
        jbAdicionar.setEnabled(condicao);
        jbCancelar.setEnabled(condicao);
        jbEmprestar.setEnabled(condicao);
    }

    private void limparCampos() {
        jtfAutor1.setText("");
        jtfAutor2.setText("");
        jlCategoria.setText("ROMANCE");
        jlQtde.setText("0");
        DefaultTableModel modelo = (DefaultTableModel) jtEmprestimoLivro.getModel();
        modelo.setNumRows(0);
    }

    private void adicionarLivroTabela() {
        @SuppressWarnings("unused")
        int codigoLivro, codigoLocador, codigoLocatario, codigoEmprestimo, quantidade = 0;

        // pegar o id do locador
        locadorModel = locadorService.getLocadorDAO(jcbLocador.getSelectedItem().toString());
        codigoLocador = locadorModel.getIdLocador();

        // pegar o id do locatario
        locatarioModel = locatarioService.getLocatarioDAO(jcbLocatario.getSelectedItem().toString());
        codigoLocatario = locatarioModel.getIdLocatario();

        // pegar o id do livro
        livroModel = livroService.getLivroDAO(jcbLivro.getSelectedItem().toString());
        codigoLivro = livroModel.getIdLivro();

        if (jlQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Você deve inserir a quantidade de livros!", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            livroModel = livroService.getLivroDAO(codigoLivro);
            locadorModel = locadorService.getLocadorDAO(codigoLocador);
            locatarioModel = locatarioService.getLocatarioDAO(codigoLocatario);

            quantidade = livroModel.getQuantidadeLivro();
            if (quantidade > 1) {
                quantidade = Integer.parseInt((JOptionPane.showInputDialog(this,
                        "Quantas unidades emprestar deste livro?", "Quantidade", JOptionPane.QUESTION_MESSAGE)));
            } else {
                quantidade = Integer.parseInt(jlQuantidade.getText());
            }
            String dataDevolucao = jtfDataDevolucao.getText();
            String dataEmprestimo = jtfDataEmprestimo.getText();

            // adiciona uma linha na tabela
            DefaultTableModel modelo = (DefaultTableModel) jtEmprestimoLivro.getModel();
            int cont = 0;
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }
            modelo.addRow(new Object[]{livroModel.getIdLivro(), livroModel.getTitulo(), locadorModel.getNome(),
                locatarioModel.getNome(), dataEmprestimo, dataDevolucao, quantidade});
        }
    }

    private void carregarLivroDevolucao() {
        DefaultTableModel modelo = (DefaultTableModel) jtDevolucaoLivro.getModel();
        // Setando a quantidade de linhas que a tabela para não haver duplicação de
        // dados
        modelo.setNumRows(0);
        try {
            // insere os produtos na tabela
            int cont = listaEmprestimoLocatarioModel.size();
            for (int i = 0; i < cont; i++) {
                if (listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getStatus().equals("ATIVO")) {
                    modelo.addRow(
                            new Object[]{listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getIdEmprestimo(),
                                listaEmprestimoLocatarioModel.get(i).getLivroModel().getTitulo(),
                                listaEmprestimoLocatarioModel.get(i).getLocatarioModel().getNome(),
                                listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getDataEmprestimo(),
                                listaEmprestimoLocatarioModel.get(i).getEmprestimoModel().getDataDevolucao()});
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar livros para preencher a tabela\n" + e.toString());
            LogModel.logClass = this.getClass().getName();
            new LogCat().writeFile(String.valueOf(e));
        }
    }

    /**
     * verifica o status antes de liberar para ele o emprestimo de um
     * determinado livro.
     */
    public void liberarEmprestimo() {
        String statusLocatario = "";
        locatarioModel = locatarioService.getLocatarioDAO(jcbLocatario.getSelectedItem().toString());
        statusLocatario = locatarioModel.getStatus();
        if (statusLocatario.equals("SUSPENSO") || statusLocatario.equals("BLOQUEADO")) {
            JOptionPane.showMessageDialog(this,
                    "O locatário está com o cadastro " + statusLocatario + ".\n"
                    + "Procure o responsável pela livraria para mais informações.\n"
                    + "O empréstimo não foi realizado.",
                    "Atenção locatário " + statusLocatario + "!", JOptionPane.WARNING_MESSAGE);
            habilitarDesabilitarCampos(false);
        } else {
            realizarEmprestimo();
        }
    }

    public void realizarEmprestimo() {
        @SuppressWarnings("unused")
        int codigoLivro = 0;
        int codigoLocador, codigoLocatario = 0;
        int codigoProduto = 0;
        int codigoEmprestimo = 0;
        // int quantidade = 0;
        String status = "ATIVO";
        listaEmprestimoLivroModel = new ArrayList<>();

        // pegar o id do locador
        locadorModel = locadorService.getLocadorDAO(jcbLocador.getSelectedItem().toString());
        codigoLocador = locadorModel.getIdLocador();

        // pegar o id do locatario
        locatarioModel = locatarioService.getLocatarioDAO(jcbLocatario.getSelectedItem().toString());
        codigoLocatario = locatarioModel.getIdLocatario();

        // pegar o id do livro
        livroModel = livroService.getLivroDAO(jcbLivro.getSelectedItem().toString());
        codigoLivro = livroModel.getIdLivro();

        int cont = jtEmprestimoLivro.getRowCount();
        for (int i = 0; i < cont; i++) {
            livroModel = new LivroModel();
            emprestimoModel = new EmprestimoModel();

            livroModel = livroService.getLivroDAO(codigoProduto);
            emprestimoLivroModel = new EmprestimoLivroModel();
            codigoProduto = (int) jtEmprestimoLivro.getValueAt(i, 0);

            // emprestimo
            emprestimoModel.setIdLocador(codigoLocador);
            emprestimoModel.setIdLocatario(codigoLocatario);
            emprestimoModel.setIdEmprestimo(codigoProduto);
            emprestimoModel.setIdLivro(codigoProduto);
            emprestimoModel.setQuantidadeEmprestimo(Integer.parseInt(jtEmprestimoLivro.getValueAt(i, 6).toString()));
            emprestimoModel.setStatus(status);
            emprestimoModel.setDataDevolucao(jtEmprestimoLivro.getValueAt(i, 5).toString());
            emprestimoModel.setDataEmprestimo(jtEmprestimoLivro.getValueAt(i, 4).toString());

            codigoEmprestimo = emprestimoService.salvarEmprestimoDAO(emprestimoModel);
            if (codigoEmprestimo > 0) {
                JOptionPane.showMessageDialog(this,
                        "Empréstimo registrado com sucesso:\n" + "Locador: " + locadorModel.getNome() + "\n"
                        + "Locatário: " + locatarioModel.getNome() + "\n" + "Data de Devolução: "
                        + emprestimoModel.getDataDevolucao() + "\n",
                        "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao registrar o empréstimo!", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }

            // emprestimo livro
            emprestimoLivroModel.setIdEmprestimoLivro(codigoProduto);
            emprestimoLivroModel.setLivro(codigoProduto);
            emprestimoLivroModel.setQuantidadeEmprestimo(emprestimoModel.getQuantidadeEmprestimo());
            emprestimoLivroModel.setEmprestimo(codigoEmprestimo);

            // livro
            livroModel.setIdLivro(codigoProduto);
            livroModel.setQuantidadeLivro(livroService.getLivroDAO(codigoProduto).getQuantidadeLivro()
                    - Integer.parseInt(jtEmprestimoLivro.getValueAt(i, 6).toString()));
            livroModel.setTitulo(livroService.getLivroDAO(codigoProduto).getTitulo());
            listaEmprestimoLivroModel.add(emprestimoLivroModel);
            listaLivroModel.add(livroModel);
        }

        // salvar os livros do empréstimo
        if (emprestimoLivroService.salvarEmprestimosLivrosDAO(listaEmprestimoLivroModel)) {
            // alterar estoque de livros
            livroService.alterarEstoqueLivroDAO(listaLivroModel);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar os livros do empréstimo!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbDevolver;
    private javax.swing.JButton jbEmprestar;
    private javax.swing.JButton jbRemoverItens;
    private javax.swing.JComboBox<String> jcbLocador;
    private javax.swing.JComboBox<String> jcbLocatario;
    private javax.swing.JComboBox<String> jcbTitulo;
    private javax.swing.JLabel jlAdicionar;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlQtde;
    private javax.swing.JTable jtAdicionarEmprestimo;
    private javax.swing.JTable jtDevolucao;
    private javax.swing.JTable jtListarEmprestimo;
    private javax.swing.JTextField jtfAutor1;
    private javax.swing.JTextField jtfAutor2;
    private javax.swing.JFormattedTextField jtfDataDevolucao;
    private javax.swing.JFormattedTextField jtfDataEmprestimo;
    // End of variables declaration//GEN-END:variables
}
