package com.biblioteca.view;

import com.biblioteca.model.LocatarioModel;
import com.biblioteca.service.LocatarioService;
import com.biblioteca.util.ColorirLinhaLocatario;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Instrutores
 */
public class FrmLocatario extends javax.swing.JInternalFrame {

    LocatarioService locatarioService = new LocatarioService();
    LocatarioModel locatarioModel = new LocatarioModel();
    ArrayList<LocatarioModel> listaLocatarioModel = new ArrayList<>();
    String alterarSalvar;

    /**
     * Creates new form FrmLocador
     *
     */
    public FrmLocatario() {
        setResizable(false);
        initComponents();
        carregarLocatario();
        carregarLocatarioPesquisa();
        limparCampos();
        corTabelaLocatario();
        corTabelaLocatarioPesquisa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jtfUf = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        jtfCep = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLocPesquisa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtLocatario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Locatário");

        jPanel2.setBackground(new java.awt.Color(0, 83, 159));

        jPanel1.setBackground(new java.awt.Color(0, 83, 159));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOVO LOCATÁRIO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N°");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BAIRRO:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UF:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TELEFONE:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-MAIL:");

        jtfRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CIDADE:");

        jtfCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfUf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/salvar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STATUS");

        jcbStatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "SUSPENSO", "BLOQUEADO" }));

        try {
            jtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jtfTelefone)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(258, 258, 258)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalvar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(114, 114, 114)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtLocPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLocPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLocPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLocPesquisa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Locatário", jPanel2);

        jtLocatario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Rua", "N°", "Bairro", "Cidade", "Cep", "UF", "Contato", "Email", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLocatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLocatarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtLocatario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver Locatário", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jbSalvar.setText("Salvar");
        limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (alterarSalvar.equals("salvar")) {
            this.salvarLocatario();
            Object[] opcoes = {"Sim", "Não"};
            Object resposta;
            resposta = JOptionPane.showInputDialog(null, "Deseja salvar outro Locatário?",
                    "Salvar Novo?", JOptionPane.OK_CANCEL_OPTION, null, opcoes, "Sim");
            if (resposta.equals("Sim")) {
                jtfNome.requestFocus();
            }
        } else if (alterarSalvar.equals("alterar")) {
            this.alterarLocatario();
        }
        carregarLocatario();
        carregarLocatarioPesquisa();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtLocPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLocPesquisaMouseClicked
        alterarSalvar = "alterar";
        jbSalvar.setText("Alterar");
        jtfNome.requestFocusInWindow();
        int linha = jtLocPesquisa.getSelectedRow();
        try {
            String nomeLocatario = (String) jtLocPesquisa.getValueAt(linha, 0);
            locatarioModel = locatarioService.getLocatarioDAO(nomeLocatario);
            jtfBairro.setText(locatarioModel.getBairroLocatario());
            jtfCep.setText(locatarioModel.getCepLocatario());
            jtfCidade.setText(locatarioModel.getCidadeLocatario());
            jtfEmail.setText(locatarioModel.getEmailLocatario());
            jtfNome.setText(locatarioModel.getNomeLocatario());
            jtfNumero.setText(locatarioModel.getNumeroLocatario());
            jtfRua.setText(locatarioModel.getLogradouroLocatario());
            jtfTelefone.setText(locatarioModel.getTelefoneLocatario());
            jtfUf.setText(locatarioModel.getEstadoLocatario());
            jcbStatus.setSelectedItem(locatarioModel.getStatusLocatario());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código invalido ou nenhum locatário selecionado",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtLocPesquisaMouseClicked

    private void jtLocatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLocatarioMouseClicked
        int linha = jtLocatario.getSelectedRow();
        String nomeLocatario = (String) jtLocatario.getValueAt(linha, 0);
        Object[] opcoes = {"Sim", "Não"};
        Object resposta;
        resposta = JOptionPane.showInputDialog(null, "Deseja excluir o Locatário?", "Excluir",
                JOptionPane.OK_CANCEL_OPTION, null, opcoes, "Sim");

        if (resposta.equals("Sim")) {
            locatarioModel = locatarioService.getLocatarioDAO(nomeLocatario);
            int codigoLocatario = locatarioModel.getIdLocatario();
            try {
                locatarioService.excluirLocatarioDAO(codigoLocatario);
                JOptionPane.showMessageDialog(this, "Locatário excluido com sucesso!", "Atenção",
                        JOptionPane.WARNING_MESSAGE);
                carregarLocatario();
                carregarLocatarioPesquisa();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o locatário!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtLocatarioMouseClicked
    private void limparCampos() {
        jtfBairro.setText("");
        jtfCep.setText("");
        jtfCidade.setText("");
        jtfEmail.setText("");
        jtfNome.setText("");
        jtfNumero.setText("");
        jtfRua.setText("");
        jtfTelefone.setText("");
        jtfUf.setText("PE");
        jcbStatus.setSelectedItem("ATIVO");
        jtfNome.requestFocus();
        this.alterarSalvar = "salvar";
        jbSalvar.setText("Salvar");
    }

    private void carregarLocatarioPesquisa() {
        listaLocatarioModel = locatarioService.getListaLocatarioDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtLocPesquisa.getModel();
        modelo.setNumRows(0);
        try {
            // insere os produtos na tabela
            int cont = listaLocatarioModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaLocatarioModel.get(i).getNomeLocatario(),
                    listaLocatarioModel.get(i).getTelefoneLocatario(),
                    listaLocatarioModel.get(i).getStatusLocatario()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar locatários para preencher a tabela\n"
                    + e.toString());
        }
    }

    private void carregarLocatario() {
        listaLocatarioModel = locatarioService.getListaLocatarioDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtLocatario.getModel();
        modelo.setNumRows(0);

        try {
            // insere os produtos na tabela
            int cont = listaLocatarioModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaLocatarioModel.get(i).getNomeLocatario(),
                    listaLocatarioModel.get(i).getLogradouroLocatario(),
                    listaLocatarioModel.get(i).getNumeroLocatario(),
                    listaLocatarioModel.get(i).getBairroLocatario(),
                    listaLocatarioModel.get(i).getCidadeLocatario(),
                    listaLocatarioModel.get(i).getCepLocatario(),
                    listaLocatarioModel.get(i).getEstadoLocatario(),
                    listaLocatarioModel.get(i).getTelefoneLocatario(),
                    listaLocatarioModel.get(i).getEmailLocatario(),
                    listaLocatarioModel.get(i).getStatusLocatario()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar locatários para preencher a tabela\n" + e.toString());
        }
    }

    private void salvarLocatario() {
        locatarioModel.setBairroLocatario(jtfBairro.getText().toUpperCase());
        locatarioModel.setCepLocatario(jtfCep.getText());
        locatarioModel.setCidadeLocatario(jtfCidade.getText().toUpperCase());
        locatarioModel.setEmailLocatario(jtfEmail.getText().toUpperCase());
        locatarioModel.setNomeLocatario(jtfNome.getText().toUpperCase());
        locatarioModel.setNumeroLocatario(jtfNumero.getText());
        locatarioModel.setLogradouroLocatario(jtfRua.getText().toUpperCase());
        locatarioModel.setTelefoneLocatario(jtfTelefone.getText());
        locatarioModel.setEstadoLocatario(jtfUf.getText().toUpperCase());
        locatarioModel.setStatusLocatario(jcbStatus.getSelectedItem().toString());
        try {
            locatarioService.salvarLocatarioDAO(locatarioModel);
            JOptionPane.showMessageDialog(this,
                    "Locatário: \n" + locatarioModel.getNomeLocatario() + "\nCadastrado com sucesso!", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            limparCampos();
            carregarLocatario();
            carregarLocatarioPesquisa();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o locatário\n" + e.toString(), "Erro",
                    JOptionPane.ERROR_MESSAGE);

        }
    }

    private void alterarLocatario() {
        locatarioModel.setBairroLocatario(jtfBairro.getText().toUpperCase());
        locatarioModel.setCepLocatario(jtfCep.getText());
        locatarioModel.setCidadeLocatario(jtfCidade.getText().toUpperCase());
        locatarioModel.setEmailLocatario(jtfEmail.getText().toUpperCase());
        locatarioModel.setNomeLocatario(jtfNome.getText().toUpperCase());
        locatarioModel.setNumeroLocatario(jtfNumero.getText());
        locatarioModel.setLogradouroLocatario(jtfRua.getText().toUpperCase());
        locatarioModel.setTelefoneLocatario(jtfTelefone.getText());
        locatarioModel.setEstadoLocatario(jtfUf.getText().toUpperCase());
        locatarioModel.setStatusLocatario(jcbStatus.getSelectedItem().toString());

        try {
            locatarioService.atualizarLocatarioDAO(locatarioModel);
            JOptionPane.showMessageDialog(this, "Locatário alterado com sucesso!", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            jbSalvar.setText("Salvar");
            carregarLocatarioPesquisa();
            carregarLocatario();
            limparCampos();
            this.jbSalvar.setText("Salvar");

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o locatário!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void corTabelaLocatario() {
        ColorirLinhaLocatario colorirLinhas = new ColorirLinhaLocatario(9);
        jtLocatario.getColumnModel().getColumn(9).setCellRenderer(colorirLinhas);
    }

    private void corTabelaLocatarioPesquisa() {
        ColorirLinhaLocatario colorirLinhaLocatario = new ColorirLinhaLocatario(2);
        jtLocPesquisa.getColumnModel().getColumn(2).setCellRenderer(colorirLinhaLocatario);
    }
    /*
    public void pesquisaLocatario() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) this.jtLocPesquisa.getModel();
            final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
            this.jtLocPesquisa.setRowSorter(classificador);
            String texto = jtfNome.getText().toUpperCase();
            classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao pesquisar o locatário!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JTable jtLocPesquisa;
    private javax.swing.JTable jtLocatario;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCep;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JTextField jtfUf;
    // End of variables declaration//GEN-END:variables
}
