package com.biblioteca.view;

import com.biblioteca.model.LocadorModel;
import com.biblioteca.service.LocadorService;
import com.biblioteca.util.CaminhosIcones;
import com.biblioteca.util.TextoPadrao;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Instrutores
 */
public class FrmLocador extends javax.swing.JInternalFrame {

    CaminhosIcones c = new CaminhosIcones();

    LocadorModel locadorModel = new LocadorModel();
    LocadorService locadorService = new LocadorService();
    ArrayList<LocadorModel> listaLocadorModel = new ArrayList<>();
    String alterarSalvar;

    /**
     * Creates new form FrmLocador
     */
    public FrmLocador() {
        setResizable(false);
        initComponents();
        carregarLocador();
        carregarLocadorPesquisa();
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jtfNome = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jtfUf = new javax.swing.JTextField();
        jtfCep = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLocPesquisa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtLocador = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Locador");

        jPanel2.setBackground(new java.awt.Color(0, 83, 159));

        jPanel1.setBackground(new java.awt.Color(0, 83, 159));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOME");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NOVO LOCADOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RUA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("N°");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BAIRRO");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UF");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CEP");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TELEFONE");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-MAIL");

        jtfRua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CIDADE");

        jtfCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/salvar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jtfUf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            jtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbCancelar)))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(258, 258, 258)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtLocPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtLocPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLocPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLocPesquisa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.addTab("Novo Locador", jPanel2);

        jtLocador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Rua", "N°", "Bairro", "Cidade", "Cep", "UF", "Contato", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLocador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLocadorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtLocador);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver Locador", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        Object[] options = {"Sim", "Não"};
        int n = JOptionPane.showOptionDialog(null, TextoPadrao.msgCancelar, TextoPadrao.msgTituloCancelar,
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, c.excluirGif, options, options[0]);
        if (n == 0) {
            jbSalvar.setText("Salvar");
            limparCampos();
            JOptionPane.showMessageDialog(null, TextoPadrao.msgCancelamento,
                    TextoPadrao.tituloJanela, JOptionPane.PLAIN_MESSAGE, c.sucessoGif);
        }
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (alterarSalvar.equals("salvar")) {
            this.salvarLocador();
            int x = JOptionPane.showConfirmDialog(null, TextoPadrao.msgSalvar, TextoPadrao.msgTituloSalvar,
                    JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, c.perguntaGif);
            if (x == 0) {
                jtfNome.requestFocus();
            }
        } else if (alterarSalvar.equals("alterar")) {
            this.alterarLocador();
        }
        carregarLocador();
        carregarLocadorPesquisa();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtLocPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLocPesquisaMouseClicked
        int linha = jtLocPesquisa.getSelectedRow();
        String locador = (String) jtLocPesquisa.getValueAt(linha, 0);
        locadorModel = locadorService.getLocadorDAO(locador);

        Object[] options = {"Sim", "Não"};
        int n = JOptionPane.showOptionDialog(null,
                "Deseja alterar este livro:\n" + locador + " ?",
                "Atenção", JOptionPane.YES_NO_OPTION,
                JOptionPane.PLAIN_MESSAGE, c.perguntaGif, options, options[0]);

        if (n == 0) {
            alterarSalvar = "alterar";
            jtfNome.requestFocusInWindow();
            //  int linha = jtLocPesquisa.getSelectedRow();
            try {
                String nomeLocador = (String) jtLocPesquisa.getValueAt(linha, 0);
                locadorModel = locadorService.getLocadorDAO(nomeLocador);
                jtfBairro.setText(locadorModel.getBairroLocador());
                jtfCep.setText(locadorModel.getCepLocador());
                jtfCidade.setText(locadorModel.getCidadeLocador());
                jtfEmail.setText(locadorModel.getEmailLocador());
                jtfNome.setText(locadorModel.getNomeLocador());
                jtfNumero.setText(locadorModel.getNumeroLocador());
                jtfRua.setText(locadorModel.getLogradouroLocador());
                jtfTelefone.setText(locadorModel.getTelefoneLocador());
                jtfUf.setText(locadorModel.getEstadoLocador());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Código inválido ou nenhum locador selecionado", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, TextoPadrao.msgCancelamento, "Atenção",
                    JOptionPane.PLAIN_MESSAGE, c.excluirGif);

        }
    }//GEN-LAST:event_jtLocPesquisaMouseClicked

    private void jtLocadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLocadorMouseClicked
        int linha = jtLocPesquisa.getSelectedRow();
        String nomeLocador = (String) jtLocPesquisa.getValueAt(linha, 0);
        // menu de opções para o usuario confirmar a exclusão
        Object[] opcoes = {"Sim", "Não"};
        Object resposta;
        resposta = JOptionPane.showInputDialog(null, "Deseja excluir o Locador?", "Excluir",
                JOptionPane.OK_CANCEL_OPTION, null, opcoes, "Sim");
        if (resposta.equals("Sim")) {
            /**
             * exclui o livro do banco de dados e atualiza a tabela
             */
            locadorModel = locadorService.getLocadorDAO(nomeLocador);
            int codigoLocador = locadorModel.getIdLocador();
            try {
                locadorService.excluirLocadorDAO(codigoLocador);
                JOptionPane.showMessageDialog(null, "Locador excluido com sucesso!", "Atenção",
                        JOptionPane.WARNING_MESSAGE);
                carregarLocador();
                carregarLocadorPesquisa();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Erro ao excluir o locador!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtLocadorMouseClicked

    private void limparCampos() {
        jtfBairro.setText("");
        jtfCep.setText("");
        jtfCidade.setText("");
        jtfEmail.setText("");
        jtfNome.setText("");
        jtfNumero.setText("");
        jtfRua.setText("");
        jtfTelefone.setText("");
        jtfUf.setText("PE");
        jtfNome.requestFocus();
        alterarSalvar = "salvar";
    }

    private void carregarLocadorPesquisa() {
        /**
         * Array que buscará no BD (atraves do Controller) os dados para serem
         * exibidos na tabela
         */
        listaLocadorModel = locadorService.getListaLocadorDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtLocPesquisa.getModel();

        // Setando a quantidade de linhas que a tabela para não haver duplicação de
        // dados
        modelo.setNumRows(0);

        try {
            // insere os produtos na tabela
            int cont = listaLocadorModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaLocadorModel.get(i).getNomeLocador(),
                    listaLocadorModel.get(i).getLogradouroLocador(),
                    listaLocadorModel.get(i).getTelefoneLocador()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar locadores para preencher a tabela");
        }
    }

    private void carregarLocador() {
        /**
         * Array que buscará no BD (atraves do Controller) os dados para serem
         * exibidos na tabela
         */
        listaLocadorModel = locadorService.getListaLocadorDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtLocador.getModel();

        // Setando a quantidade de linhas que a tabela para não haver duplicação de
        // dados
        modelo.setNumRows(0);
        try {
            // insere os produtos na tabela
            int cont = listaLocadorModel.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(
                        new Object[]{
                            listaLocadorModel.get(i).getNomeLocador(),
                            listaLocadorModel.get(i).getLogradouroLocador(),
                            listaLocadorModel.get(i).getNumeroLocador(),
                            listaLocadorModel.get(i).getBairroLocador(),
                            listaLocadorModel.get(i).getCidadeLocador(),
                            listaLocadorModel.get(i).getEstadoLocador(),
                            listaLocadorModel.get(i).getCepLocador(),
                            listaLocadorModel.get(i).getTelefoneLocador(),
                            listaLocadorModel.get(i).getEmailLocador()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar locadores para preencher a tabela");
        }
    }

    private void salvarLocador() {
        locadorModel.setBairroLocador(jtfBairro.getText().toUpperCase());
        locadorModel.setCepLocador(jtfCep.getText());
        locadorModel.setCidadeLocador(jtfCidade.getText().toUpperCase());
        locadorModel.setEmailLocador(jtfEmail.getText());
        locadorModel.setNomeLocador(jtfNome.getText().toUpperCase());
        locadorModel.setNumeroLocador(jtfNumero.getText());
        locadorModel.setLogradouroLocador(jtfRua.getText().toUpperCase());
        locadorModel.setTelefoneLocador(jtfTelefone.getText());
        locadorModel.setEstadoLocador(jtfUf.getText().toUpperCase());
        try {
            if (locadorService.salvarLocadorDAO(locadorModel)) {
                JOptionPane.showMessageDialog(this, "Locador: \n" + locadorModel.getNomeLocador() + "\nCadastrado com sucesso!",
                        "Atenção", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                carregarLocador();
                carregarLocadorPesquisa();
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o locador\n" + e.toString(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarLocador() {
        locadorModel.setBairroLocador(jtfBairro.getText().toUpperCase());
        locadorModel.setCepLocador(jtfCep.getText());
        locadorModel.setCidadeLocador(jtfCidade.getText().toUpperCase());
        locadorModel.setEmailLocador(jtfEmail.getText().toUpperCase());
        locadorModel.setNomeLocador(jtfNome.getText().toUpperCase());
        locadorModel.setNumeroLocador(jtfNumero.getText());
        locadorModel.setLogradouroLocador(jtfRua.getText().toUpperCase());
        locadorModel.setTelefoneLocador(jtfTelefone.getText());
        locadorModel.setEstadoLocador(jtfUf.getText().toUpperCase());
        try {
            locadorService.atualizarLocadorDAO(locadorModel);
            JOptionPane.showMessageDialog(this, "Locador alterado com sucesso!", "Atenção",
                    JOptionPane.WARNING_MESSAGE);
            jbSalvar.setText("Salvar");
            carregarLocadorPesquisa();
            carregarLocador();
            limparCampos();
            this.jbSalvar.setText("Salvar");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o locador!", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTable jtLocPesquisa;
    private javax.swing.JTable jtLocador;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCep;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JFormattedTextField jtfTelefone;
    private javax.swing.JTextField jtfUf;
    // End of variables declaration//GEN-END:variables
}
