package com.biblioteca.view;

import com.biblioteca.model.LivroModel;
import com.biblioteca.model.SessaoUsuarioModel;
import com.biblioteca.service.LivroService;
import com.biblioteca.util.CaminhosIcones;
import com.biblioteca.util.ColorirLinhaLivro;
import com.biblioteca.util.GetDateUtil;
import com.biblioteca.util.TextoPadrao;
import java.awt.HeadlessException;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Instrutores
 */
public class FrmLivro extends javax.swing.JInternalFrame {

    LivroModel livroModel = new LivroModel();
    LivroService livroService = new LivroService();
    ArrayList<LivroModel> listaModelLivro = new ArrayList<>();
    String alterarSalvar, tipoLivro;
    double valorLivro = 0;
    GetDateUtil getDateUtil = new GetDateUtil();
    CaminhosIcones c = new CaminhosIcones();

    /**
     * Creates new form FrmLivro
     *
     */
    public FrmLivro() {
        initComponents();
        setarDados();
        carregarLivros();
        carregarLivrosPesquisa();
        limparCampos();
        colorirLinhas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jtfAutor1 = new javax.swing.JTextField();
        jtfEditora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfAno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfDataCadastro = new javax.swing.JFormattedTextField();
        jtfQtde = new javax.swing.JTextField();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfObs = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jcEmprestimo = new javax.swing.JCheckBox();
        jcVenda = new javax.swing.JCheckBox();
        jlUsuarioLogado = new javax.swing.JLabel();
        jlNivelUsuario = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jcbGenero = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jlIdLivro = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtLivroPesquisa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtLivro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("GERENCIAMENTO DE LIVROS");

        jPanel1.setBackground(new java.awt.Color(28, 89, 124));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TÍTULO");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AUTOR(A)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EDITORA");

        jtfTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfAutor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfEditora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GÊNERO LITERÁRIO");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ANO LANÇAMENTO");

        jtfAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA CADASTRO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QUANTIDADE");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ESTADO CONSERVAÇÃO");

        try {
            jtfDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfDataCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jtfQtde.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfQtde.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jcbEstado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOVO", "USADO", "OUTRO" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DESCRIÇÃO GERAL(OBSERVAÇÕES GERAIS)");

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jtfObs.setColumns(20);
        jtfObs.setRows(5);
        jScrollPane1.setViewportView(jtfObs);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SELECIONE O TIPO DE CADASTRO");

        jcEmprestimo.setBackground(new java.awt.Color(28, 89, 124));
        jcEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jcEmprestimo.setText("EMPRÉSTIMO");
        jcEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEmprestimoActionPerformed(evt);
            }
        });

        jcVenda.setBackground(new java.awt.Color(28, 89, 124));
        jcVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jcVenda.setForeground(new java.awt.Color(255, 255, 255));
        jcVenda.setText("VENDA");
        jcVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVendaActionPerformed(evt);
            }
        });

        jlUsuarioLogado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlUsuarioLogado.setText("$Usuario Logado");

        jlNivelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNivelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlNivelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNivelUsuario.setText("$Nivel de Acesso");

        jbCancelar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/biblioteca/images/actions/salvar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jcbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codificação", "Romance", "Doutrinário", "Outro" }));
        jcbGenero.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbGeneroPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("ID LIVRO");

        jlIdLivro.setBackground(new java.awt.Color(51, 51, 51));
        jlIdLivro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jlIdLivro.setForeground(new java.awt.Color(204, 204, 204));
        jlIdLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIdLivro.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jbCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSalvar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jlIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jcEmprestimo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcVenda))))
                        .addComponent(jtfTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                            .addComponent(jtfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfAutor1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(55, 55, 55)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfEditora)
                                .addComponent(jtfAno)
                                .addComponent(jcbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jlUsuarioLogado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlNivelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcVenda)
                            .addComponent(jcEmprestimo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jlIdLivro))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuarioLogado)
                    .addComponent(jlNivelUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtLivroPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Título", "Autor", "Qtde"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLivroPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLivroPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtLivroPesquisa);
        if (jtLivroPesquisa.getColumnModel().getColumnCount() > 0) {
            jtLivroPesquisa.getColumnModel().getColumn(0).setPreferredWidth(120);
            jtLivroPesquisa.getColumnModel().getColumn(1).setResizable(false);
            jtLivroPesquisa.getColumnModel().getColumn(1).setPreferredWidth(80);
            jtLivroPesquisa.getColumnModel().getColumn(2).setResizable(false);
            jtLivroPesquisa.getColumnModel().getColumn(2).setPreferredWidth(9);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Livro", jPanel2);

        jtLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Editora", "Gênero", "Ano", "Data", "Qtde", "Estado", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLivroMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtLivro);
        if (jtLivro.getColumnModel().getColumnCount() > 0) {
            jtLivro.getColumnModel().getColumn(0).setPreferredWidth(90);
            jtLivro.getColumnModel().getColumn(1).setPreferredWidth(90);
            jtLivro.getColumnModel().getColumn(2).setResizable(false);
            jtLivro.getColumnModel().getColumn(2).setPreferredWidth(30);
            jtLivro.getColumnModel().getColumn(3).setResizable(false);
            jtLivro.getColumnModel().getColumn(3).setPreferredWidth(40);
            jtLivro.getColumnModel().getColumn(4).setResizable(false);
            jtLivro.getColumnModel().getColumn(4).setPreferredWidth(7);
            jtLivro.getColumnModel().getColumn(5).setResizable(false);
            jtLivro.getColumnModel().getColumn(5).setPreferredWidth(25);
            jtLivro.getColumnModel().getColumn(6).setResizable(false);
            jtLivro.getColumnModel().getColumn(6).setPreferredWidth(9);
            jtLivro.getColumnModel().getColumn(7).setResizable(false);
            jtLivro.getColumnModel().getColumn(7).setPreferredWidth(20);
            jtLivro.getColumnModel().getColumn(8).setResizable(false);
            jtLivro.getColumnModel().getColumn(8).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver Livros", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        jbSalvar.setText("Salvar");
        limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (alterarSalvar.equals("salvar")) {
            this.salvarLivro();
        } else if (alterarSalvar.equals("alterar")) {
            this.alterarLivro();
        }
        carregarLivros();
        carregarLivrosPesquisa();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jtLivroPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLivroPesquisaMouseClicked
        int linha = jtLivroPesquisa.getSelectedRow();
        String tituloLivro = (String) jtLivroPesquisa.getValueAt(linha, 0);
        livroModel = livroService.getLivroDAO(tituloLivro);

        Object[] options = {"Sim", "Não"};
        int n = JOptionPane.showOptionDialog(null,
                "Deseja alterar este livro:\n" + tituloLivro + " ?",
                "Atenção", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (n == 0) {
            alterarSalvar = "alterar";
            try {
                jlIdLivro.setText(String.valueOf(livroModel.getIdLivro()));
                jtfAno.setText(String.valueOf(livroModel.getAnoLivro()));
                jtfAutor1.setText(livroModel.getAutor1Livro());
                jtfEditora.setText(livroModel.getEditoraLivro());
                jcbGenero.setSelectedItem(livroModel.getGeneroLivro());
                jtfDataCadastro.setText(livroModel.getDataCadastroLivro());
                jtfObs.setText(livroModel.getDescricaoLivro());
                jtfTitulo.setText(livroModel.getTituloLivro());
                jtfQtde.setText(String.valueOf(livroModel.getQtdeLivro()));
                jcbEstado.setSelectedItem(livroModel.getEstadoLivro());
                this.tipoLivro = livroModel.getTipoLivro();
                if (this.tipoLivro.equals("VENDA")) {
                    jcVenda.setSelected(true);
                } else {
                    jcEmprestimo.setSelected(true);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Código invalido ou nenhum livro selecionado", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "O livro selecionado não foi alterado!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtLivroPesquisaMouseClicked

    private void jtLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLivroMouseClicked
        int linha = jtLivro.getSelectedRow();
        String tituloLivro = (String) jtLivro.getValueAt(linha, 0);

        Object[] opcoes = {"Sim", "Não"};
        Object resposta;
        resposta = JOptionPane.showInputDialog(null, "Deseja excluir o livro?", "Excluir?",
                JOptionPane.OK_CANCEL_OPTION, null, opcoes, "Sim");
        if (resposta.equals("Sim")) {
            livroModel = livroService.getLivroDAO(tituloLivro);
            int codigoLivro = livroModel.getIdLivro();
            if (livroService.excluirLivroDAO(codigoLivro)) {
                JOptionPane.showMessageDialog(this, "Livro excluido com sucesso!", "Atenção",
                        JOptionPane.WARNING_MESSAGE);
                carregarLivros();
                carregarLivrosPesquisa();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir o livro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jtLivroMouseClicked

    private void jcEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEmprestimoActionPerformed
        this.jcVenda.setSelected(false);
        this.jcEmprestimo.setSelected(true);
        this.tipoLivro = "EMPRÉSTIMO";
    }//GEN-LAST:event_jcEmprestimoActionPerformed

    private void jcVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVendaActionPerformed
        this.jcVenda.setSelected(true);
        this.jcEmprestimo.setSelected(false);
        this.tipoLivro = "VENDA";
        this.valorLivro = Double.parseDouble(JOptionPane.showInputDialog(this, "INSIRA O VALOR DO LIVRO", "Valor", JOptionPane.QUESTION_MESSAGE));
    }//GEN-LAST:event_jcVendaActionPerformed

    private void jcbGeneroPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbGeneroPopupMenuWillBecomeInvisible
        pegarDadosGenero();
    }//GEN-LAST:event_jcbGeneroPopupMenuWillBecomeInvisible

    private void carregarLivrosPesquisa() {
        listaModelLivro = livroService.getListaLivroDAO();
        DefaultTableModel modelo = (DefaultTableModel) jtLivroPesquisa.getModel();
        modelo.setNumRows(0);
        try {
            int cont = listaModelLivro.size();
            for (int i = 0; i < cont; i++) {
                modelo.addRow(new Object[]{
                    listaModelLivro.get(i).getTituloLivro(),
                    listaModelLivro.get(i).getAutor1Livro(),
                    listaModelLivro.get(i).getQtdeLivro()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar livros para preencher a tabela\n" + e.toString());
        }
    }

    private void carregarLivros() {
        listaModelLivro = livroService.getListaLivroDAO();
        DefaultTableModel modeloTabela = (DefaultTableModel) jtLivro.getModel();
        modeloTabela.setNumRows(0);
        try {
            int cont = listaModelLivro.size();
            for (int i = 0; i < cont; i++) {
                modeloTabela.addRow(new Object[]{
                    listaModelLivro.get(i).getTituloLivro(),
                    listaModelLivro.get(i).getAutor1Livro(),
                    listaModelLivro.get(i).getEditoraLivro(),
                    listaModelLivro.get(i).getGeneroLivro(),
                    listaModelLivro.get(i).getAnoLivro(),
                    listaModelLivro.get(i).getDataCadastroLivro(),
                    listaModelLivro.get(i).getQtdeLivro(),
                    listaModelLivro.get(i).getEstadoLivro(),
                    listaModelLivro.get(i).getDescricaoLivro()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar livros para preencher a tabela\n" + e.toString());
        }
    }

    private void limparCampos() {
        jtfAno.setText("");
        jtfAutor1.setText("");
        jtfEditora.setText("");
        jtfObs.setText("");
        jtfTitulo.setText("");
        jcVenda.setSelected(false);
        jcEmprestimo.setSelected(false);
        jcbGenero.setSelectedItem("CodificaçãoS");
        jcbEstado.setSelectedItem("NOVO");
        alterarSalvar = "salvar";
        jtfDataCadastro.setText(new GetDateUtil().setarDataPadraoUs());
        jlIdLivro.setText(String.valueOf(livroService.ultimoIdLivro()));

    }

    /**
     *
     */
    private void salvarLivro() {
        livroModel.setAnoLivro(jtfAno.getText());
        livroModel.setAutor1Livro(jtfAutor1.getText().toUpperCase());
        livroModel.setEditoraLivro(jtfEditora.getText().toUpperCase());
        livroModel.setDataCadastroLivro(jtfDataCadastro.getText());
        livroModel.setGeneroLivro(jcbGenero.getSelectedItem().toString().toUpperCase());
        livroModel.setDescricaoLivro(jtfObs.getText().toUpperCase());
        livroModel.setTituloLivro(jtfTitulo.getText().toUpperCase());
        livroModel.setTipoLivro(this.tipoLivro);
        livroModel.setQtdeLivro(Integer.parseInt(jtfQtde.getText()));
        livroModel.setEstadoLivro(jcbEstado.getSelectedItem().toString());
        livroModel.setValorLivro(this.valorLivro);
        if (jcEmprestimo.isSelected() || jcVenda.isSelected()) {
            try {
                if (livroService.salvarLivroDAO(livroModel)) {
                    JOptionPane.showMessageDialog(this, "O livro foi cadastrado com sucesso!",
                            "Atenção", JOptionPane.WARNING_MESSAGE);
                    limparCampos();
                }
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o livro\n" + e.toString(), "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, TextoPadrao.msgTipoLivro,
                    TextoPadrao.tituloJanela, HEIGHT, c.atencaoGif);
        }
    }

    /**
     *
     */
    private void alterarLivro() {
        livroModel.setAnoLivro(jtfAno.getText());
        livroModel.setAutor1Livro(jtfAutor1.getText().toUpperCase());
        livroModel.setEditoraLivro(jtfEditora.getText().toUpperCase());
        livroModel.setDataCadastroLivro(jtfDataCadastro.getText());
        livroModel.setGeneroLivro(jcbGenero.getSelectedItem().toString().toUpperCase());
        livroModel.setDescricaoLivro(jtfObs.getText().toUpperCase());
        livroModel.setTituloLivro(jtfTitulo.getText().toUpperCase());
        livroModel.setTipoLivro(this.tipoLivro);
        livroModel.setQtdeLivro(Integer.parseInt(jtfQtde.getText()));
        livroModel.setEstadoLivro(jcbEstado.getSelectedItem().toString());
        livroModel.setValorLivro(this.valorLivro);

        try {
            if (livroService.atualizarLivroDAO(livroModel)) {
                JOptionPane.showMessageDialog(this, "Livro alterado com sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                jbSalvar.setText("Salvar");
                carregarLivrosPesquisa();
                carregarLivros();
                limparCampos();
                this.jbSalvar.setText("Salvar");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o livro!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setarDados() {
        jtfDataCadastro.setText(getDateUtil.setarData());
        jlIdLivro.setText(String.valueOf(livroService.ultimoIdLivro()));
        jlUsuarioLogado.setText(SessaoUsuarioModel.codigoUsuario + " - " + SessaoUsuarioModel.nomeUsuario);
        jlNivelUsuario.setText(SessaoUsuarioModel.nivelAcesso);
    }

    private void pegarDadosGenero() {
        if (jcbGenero.getSelectedItem().equals("Outro")) {
            String x = JOptionPane.showInputDialog(null, "INSIRA AQUI O GêNERO");
            JOptionPane.showMessageDialog(null, x);
        }
    }

    private void colorirLinhas() {
        ColorirLinhaLivro colorirLinhaLivro1 = new ColorirLinhaLivro(6);
        jtLivro.getColumnModel().getColumn(6).setCellRenderer(colorirLinhaLivro1);

        ColorirLinhaLivro colorirLinhaLivro2 = new ColorirLinhaLivro(7);
        jtLivro.getColumnModel().getColumn(7).setCellRenderer(colorirLinhaLivro2);

        ColorirLinhaLivro colorirLinhaLivro3 = new ColorirLinhaLivro(2);
        jtLivroPesquisa.getColumnModel().getColumn(2).setCellRenderer(colorirLinhaLivro3);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JCheckBox jcEmprestimo;
    private javax.swing.JCheckBox jcVenda;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbGenero;
    private javax.swing.JLabel jlIdLivro;
    private javax.swing.JLabel jlNivelUsuario;
    private javax.swing.JLabel jlUsuarioLogado;
    private javax.swing.JTable jtLivro;
    private javax.swing.JTable jtLivroPesquisa;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfAutor1;
    private javax.swing.JFormattedTextField jtfDataCadastro;
    private javax.swing.JTextField jtfEditora;
    private javax.swing.JTextArea jtfObs;
    private javax.swing.JTextField jtfQtde;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
